USER_CUSTOMER = "CU"
USER_DRIVER = "DR"
USER_PROVIDER = "PR"

USER_CHOICES = (
    (USER_CUSTOMER, "Customer"),
    (USER_DRIVER, "Driver"),
    (USER_PROVIDER, "Provider"),
)

SERVICE_FOOD_DELIVERY = "FD"
SERVICE_CAR_RENTAL = "CA"
SERVICE_MAINTENANCE_SERVICE = "MS"
SERVICE_DELIVERY_SERVICE = "DS"
SERVICE_ONLINE_STORE = "OS"

SERVICE_CHOICES = (
    (SERVICE_FOOD_DELIVERY, "Food Delivery"),
    (SERVICE_CAR_RENTAL, "Car Rental"),
    (SERVICE_MAINTENANCE_SERVICE, "Maintenance Service"),
    (SERVICE_DELIVERY_SERVICE, "Delivery Service"),
    (SERVICE_ONLINE_STORE, "Online Store"),
)
